### ISSUE TITLE
运行GitHub上这个项目

### ISSUE THREAD

**Issue by xuxing1995** [MixinNetwork/developers.mixin.one#40]
这个github项目的运行文件是哪一个，如何运行起来

**Comment by xuxing1995** [comment]
这个项目中引用的一个npm包已被废弃（bugsnag-js）

**Comment by imjasonwww** [comment]
https://github.com/MixinNetwork/developers.mixin.one/blob/master/package.json#L41

这是运行命令

**Comment by jadeydi** [comment]
https://github.com/MixinNetwork/developers.mixin.one/blob/master/package.json#L41

这里是运行命令
