### ISSUE TITLE
OAuth scope 的编码处理存在问题

### ISSUE THREAD

**Issue by lyricat** [MixinNetwork/developers.mixin.one#41]
scope 使用 + 来分割不同 permissions
OAuth 时， 例如 

```
https://mixin.one/oauth/authorize?client_id=CLIENT_ID&scope=PROFILE:READ+ASSETS:READ&response_type=code
```

的 `PROFILE:READ+ASSETS:READ` url component encode 后应该 `PROFILE%3AREAD%2BASSETS%3AREAD`，但是 Mixin OAuth 不能正常识别 + 编码后的 %2B。

**Comment by lyricat** [comment]
使用 %2B 页面会提示 ERROR
把 %2B 换成 + 能够正常显示。

**Comment by imjasonwww** [comment]
scopes 的区别是 space 不是 %2B, 所以换成 %20 应该是可以的

**Comment by jadeydi** [comment]
scopes 的区别是 space 不是 %2B, 所以换成 %20 应该是可以的

**Comment by lyricat** [comment]
但是文档上是用加号分隔的…

**Comment by jadeydi** [comment]
https://en.wikipedia.org/wiki/Query_string

SPACE is encoded as '+' or '%20'
所以要么用 + 要么用 %20

**Comment by lyricat** [comment]
我明白了，不能直接用 encodeURIComponent

**Comment by cedricfung** [comment]
能用 encodeURIComponent，只不过 OAuth 标准是要用空格分隔 scopes 不是用 +，空格就会被自动 encode 成 %20 啊，你不能 encode 两次。
