### ISSUE TITLE
中文内容的改进意见

### ISSUE THREAD

**Issue by happypeter** [MixinNetwork/developers.mixin.one#451]
翻译英文的过程中发现有些中文内容似乎需要改进，总结到这里。

**Comment by happypeter** [comment]
https://github.com/MixinNetwork/developers.mixin.one/blob/main/developers/src/i18n/zh/document/mainnet/mtg/exchange.md
`现价单` 是否应该是 `限价单`?

**Comment by happypeter** [comment]
https://github.com/MixinNetwork/developers.mixin.one/blob/main/developers/src/i18n/zh/document/mainnet/mtg/wappercoin.md 这个文件的文件名，建议改成 `wrappedtoken` 

参考 https://blog.liquid.com/wrapped-tokens

**Comment by happypeter** [comment]
https://github.com/MixinNetwork/developers.mixin.one/blob/main/developers/src/i18n/zh/document/wallet/overview.md
`31 条主链` -> `32 条主链`
以便与 https://github.com/MixinNetwork/developers.mixin.one/blob/main/developers/src/i18n/zh/document/mainnet/overview.md 一致

**Comment by happypeter** [comment]
https://github.com/MixinNetwork/developers.mixin.one/blob/main/developers/src/i18n/zh/document/wallet/get-started/create-app.md `/dashboard` 这个可能是死链接

**Comment by happypeter** [comment]
https://github.com/MixinNetwork/developers.mixin.one/blob/main/developers/src/i18n/zh/document/wallet/get-started/authentication-token.md
`授权令牌` -> `认证令牌`

**Comment by happypeter** [comment]
https://developers.mixin.one/document/wallet/api/session-secret

最后的 json 括号不配对

**Comment by lyricat** [comment]
document 下的文档是老版，应该不需要维护了。
